services:
  webapp:
    container_name: "app"
    build: webapp/.
    ports:
      - 3000:3000
      - 8080:8080

    volumes:
      - ./webapp/volume:/app
    secrets:
      - Root_pw

# secrets:
#   Root_pw: 
#     file: ./webapp/secrets/Root_pw.txt